# Generated by Django 3.1.4 on 2021-01-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210117_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='trailing_pe',
        ),
    ]
