# Generated by Django 3.1.4 on 2021-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210117_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='volume',
        ),
    ]
