# Generated by Django 3.1.4 on 2021-01-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_remove_statistics_forward_pe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statistics",
            name="book_value",
        ),
        migrations.RemoveField(
            model_name="statistics",
            name="forward_eps",
        ),
        migrations.RemoveField(
            model_name="statistics",
            name="profit_margins",
        ),
        migrations.RemoveField(
            model_name="statistics",
            name="trailing_eps",
        ),
    ]
