# Generated by Django 3.1.4 on 2021-02-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20210124_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='regular_market_change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
