# Generated by Django 3.1.4 on 2021-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imgSrc', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('links', models.CharField(max_length=240)),
                ('technologies', models.CharField(max_length=120)),
                ('keywords', models.CharField(max_length=120)),
                ('demoSrc', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
