# Generated by Django 3.1.4 on 2021-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0011_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
