# Generated by Django 3.1.4 on 2021-06-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_remove_blog_imgsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pretext',
            field=models.CharField(default='Sample text', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
