# Generated by Django 3.1.4 on 2021-06-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0014_auto_20210615_2338"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="technologies",
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.CharField(
                default="Deep RL, Tensorflow, Python", max_length=240
            ),
            preserve_default=False,
        ),
    ]
